### ISSUE TITLE
Error: Invalid names for the covariates or associated uncertainty in MA analysis

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/distance-bugs#137]
The following error is generated when you try to incorporate covariate uncertainty:

Error: Invalid names for the covariates or associated uncertainty have been specified in the covariate uncertainty dataframe.
Execution halted

**Comment by LHMarshall** [comment]
This error is due to a mis-communication between Distance 7 and mads. Distance 7 changes the names of the covariates before passing them to mrds but mads still recieves the unmodified covariate names.

This will be fixed in the next release of Distance 7. However, as a temporary solution you can download and install a patched version of mads that makes the same alterations to the covariate names as Distance 7.

library(devtools)
install_github("LHMarshall/mads/mads@Distance7-patch")

**Comment by LHMarshall** [comment]
Fixed in Distance 7 beta
